export type AppLanguage = 'zh-CN' | 'en-US'
export type TranslationValues = Readonly<Record<string, string | number>>

const ENGLISH_MESSAGES: Readonly<Record<string, string>> = {
  '设置': 'Settings',
  '第 {page} 页': 'Page {page}',
  '文件': 'File',
  '编辑': 'Edit',
  '窗口': 'Window',
  '退出 Sonavi': 'Quit Sonavi',
  '撤销': 'Undo',
  '重做': 'Redo',
  '剪切': 'Cut',
  '复制': 'Copy',
  '粘贴': 'Paste',
  '全选': 'Select All',
  '最小化': 'Minimize',
  '关闭窗口': 'Close Window',
  '显示 Sonavi': 'Show Sonavi',
  '暂停': 'Pause',
  '播放': 'Play',
  '上一首': 'Previous',
  '下一首': 'Next',
  '重启 Sonavi': 'Restart Sonavi',
  '简体中文': 'Simplified Chinese',
  '英文': 'English',
  '平台': 'Platform',
  '服务器': 'Server',
  '协议版本': 'Protocol version',
  '转码跳转': 'Transcoded seeking',
  '服务器已声明 transcodeOffset': 'The server declares transcodeOffset support',
  '未确认支持，将禁用转码进度跳转': 'Not confirmed; transcoded seeking is disabled',
  '后台播放': 'Background playback',
  '托盘 / 菜单栏驻留；选择“退出 Sonavi”才停止播放宿主': 'Stays in the tray or menu bar; choose “Quit Sonavi” to stop playback',
  '桌面行为': 'Desktop behavior',
  '关闭窗口时': 'When closing the window',
  '隐藏窗口并继续播放（默认）': 'Hide the window and keep playing (default)',
  '外观': 'Appearance',
  '跟随系统': 'Use system setting',
  '浅色': 'Light',
  '深色': 'Dark',
  '界面语言': 'Interface language',
  '最小化始终保留播放。隐藏后可从 Windows 托盘或 macOS 菜单栏重新显示；托盘菜单中的“退出 Sonavi”会停止播放并退出进程。': 'Minimizing always keeps playback active. Reopen a hidden window from the Windows tray or macOS menu bar; “Quit Sonavi” stops playback and exits the process.',
  '正在保存…': 'Saving…',
  '保存桌面设置': 'Save desktop settings',
  '桌面设置已保存。关闭窗口时将按新规则执行。': 'Desktop settings saved. The new window-close behavior is active.',
  '桌面设置保存失败。': 'Could not save desktop settings.',
  '设置保存失败': 'Could not save settings',
  '播放策略': 'Playback policy',
  '模式': 'Mode',
  '播放模式': 'Playback mode',
  '自动（已知格式优先原始，否则兼容转码）': 'Automatic (prefer original for known formats, otherwise transcode)',
  '仅原始音频': 'Original audio only',
  'MP3 兼容转码': 'Compatible MP3 transcoding',
  '转码最高码率': 'Maximum transcoding bitrate',
  '自动模式的原始音频若发生浏览器解码错误，只尝试一次兼容转码；不会无限重试。': 'If original audio fails to decode in automatic mode, Sonavi tries compatible transcoding once and never retries indefinitely.',
  '网络代理': 'Network proxy',
  '代理模式': 'Proxy mode',
  '跟随系统代理': 'Use system proxy',
  '直接连接': 'Direct connection',
  '手动代理': 'Manual proxy',
  '代理地址': 'Proxy address',
  'API、封面和音频共用此策略。切换代理会关闭旧连接；失败时不会静默改为直连。': 'API, cover art, and audio share this policy. Changing the proxy closes existing connections; failures never silently fall back to a direct connection.',
  '保存播放与网络设置': 'Save playback and network settings',
  '设置已保存；代理已切换，旧连接和当前播放已安全停止。': 'Settings saved. The proxy changed, so old connections and current playback were safely stopped.',
  '播放设置已保存；当前歌曲会尽量从原进度切换，否则下一曲生效。': 'Playback settings saved. The current track will switch from its current position when possible; otherwise the next track uses the new policy.',
  '设置已保存；当前队列与播放保持不变。': 'Settings saved. The current queue and playback are unchanged.',
  '请检查代理地址、端口和网络状态。': 'Check the proxy address, port, and network status.',
  '网络设置保存失败': 'Could not save network settings',
  '连接诊断': 'Connection diagnostics',
  '仅记录阶段、端点名、状态、类型、分类、耗时与脱敏后的错误文本，不记录 URL、账号、token、资源 ID 或响应正文。': 'Records only the stage, endpoint name, status, type, category, timing, and redacted error text. URLs, accounts, tokens, resource IDs, and response bodies are never recorded.',
  '刷新': 'Refresh',
  '导出': 'Export',
  '暂无请求记录；使用音乐库或播放后再刷新。': 'No requests recorded yet. Use the library or play music, then refresh.',
  '第 {attempt} 次': 'Attempt {attempt}',
  '无类型': 'No type',
  '排队 {duration} ms': 'Queued {duration} ms',
  '上游 {duration} ms': 'Upstream {duration} ms',
  '响应头 {duration} ms': 'Headers {duration} ms',
  '已读 {size}': 'Read {size}',
  '封面': 'Cover art',
  '原始音频': 'Original audio',
  '转码音频': 'Transcoded audio',
  '播放缓冲': 'Playback buffering',
  '封面缓存': 'Cover cache',
  '按账号隔离、最近最少使用淘汰，单账号上限 128 MiB；不缓存音频，不提供离线下载。': 'Isolated by account and evicted by least-recently-used order, with a 128 MiB limit per account. Audio is never cached and offline downloads are not provided.',
  '正在清理…': 'Clearing…',
  '清空当前账号缓存': 'Clear current account cache',
  '当前账号的封面缓存已清空；音频从未写入离线缓存。': 'The current account’s cover cache was cleared. Audio has never been written to the offline cache.',
  '封面缓存清理失败。': 'Could not clear the cover cache.',
  '缓存清理失败': 'Could not clear cache',
  '应用恢复': 'Application recovery',
  '界面或播放状态异常时，可关闭当前进程并重新打开 Sonavi。当前队列会按既有退出流程保存，并在重启后以暂停状态恢复；若整个应用已无法响应，仍需使用系统强制退出。': 'If the interface or playback state becomes abnormal, restart Sonavi. The current queue is saved through the normal quit flow and restored paused; use the operating system to force quit if the whole app is unresponsive.',
  '正在重启…': 'Restarting…',
  '断开连接': 'Disconnect',
  '退出并忘记账号': 'Sign out and forget account',
  '清空当前账号的封面缓存？': 'Clear the current account’s cover cache?',
  '将删除当前账号在本机的所有封面缓存，不会删除服务器上的音乐。之后浏览时需重新下载封面。': 'This deletes all locally cached cover art for the current account. Music on the server is not affected, and covers will be downloaded again as you browse.',
  '清空缓存': 'Clear cache',
  '断开当前连接？': 'Disconnect the current session?',
  '将停止当前播放并退出此会话。已保存的加密凭据会保留，下次启动时仍可自动恢复。': 'This stops current playback and ends the session. Saved encrypted credentials remain available for automatic restore on the next launch.',
  '确认断开': 'Disconnect',
  '重启 Sonavi？': 'Restart Sonavi?',
  '当前播放会停止，队列将保存并在新进程中以暂停状态恢复。尚未保存的设置修改不会保留。': 'Current playback will stop. The queue is saved and restored paused in the new process. Unsaved setting changes will be discarded.',
  '确认重启': 'Restart',
  '无法读取网络与播放设置。': 'Could not load network and playback settings.',
  '设置加载失败': 'Could not load settings',
  '无法请求重启，请先保存工作后手动退出并重新打开 Sonavi。': 'Could not request a restart. Save your work, quit Sonavi manually, and open it again.',
  '重启失败': 'Restart failed',
  '已导出脱敏且限量的诊断日志。': 'Exported a redacted, size-limited diagnostic log.',
  '诊断日志导出失败。': 'Could not export the diagnostic log.',
  '导出失败': 'Export failed',
  '操作失败': 'Operation failed',
  '确认': 'Confirm',
  '取消': 'Cancel',
  '正在处理…': 'Working…',
  '返回': 'Back',
  '应用启动失败': 'Application startup failed',
  '无法打开项目主页': 'Could not open project homepage',
  '账号操作失败': 'Account operation failed',
  '播放记录同步失败': 'Could not sync playback history',
  '播放失败': 'Playback failed',
  '无法读取受信任的应用信息，请重新启动 Sonavi。': 'Could not read trusted application information. Restart Sonavi.',
  '无法调用系统默认浏览器，请稍后重试。': 'Could not open the system browser. Try again later.',
  '无法安全断开当前会话，请重新启动 Sonavi。': 'Could not safely disconnect the current session. Restart Sonavi.',
  '无法验证服务器切换结果，请重新启动 Sonavi。': 'Could not verify the server switch. Restart Sonavi.',
  '无法删除保存的凭据；当前界面未退出，请重试。': 'Could not delete the saved credentials. The current session remains active; try again.',
  '主导航': 'Main navigation',
  '在浏览器中打开 Sonavi GitHub 仓库': 'Open the Sonavi GitHub repository in a browser',
  '连接服务器': 'Connect to server',
  '音乐': 'Music',
  '专辑': 'Albums',
  '艺术家': 'Artists',
  '收藏': 'Favorites',
  '歌单': 'Playlists',
  '设置快捷键 {shortcut}': 'Settings shortcut {shortcut}',
  'Subsonic 服务器': 'Subsonic server',
  '全部专辑': 'All albums',
  '正在读取应用信息…': 'Loading application information…',
  '退出并忘记账号？': 'Sign out and forget this account?',
  '将删除这台设备上保存的加密凭据、暂停队列和当前账号封面缓存。': 'This deletes the encrypted credentials, paused queue, and cover cache saved for the current account on this device.',
  '退出并删除': 'Sign out and delete',
  'Sonavi 通知': 'Sonavi notifications',
  '音乐列表加载失败。': 'Could not load the music list.',
  '音乐列表加载失败': 'Could not load music',
  '搜索歌曲': 'Search songs',
  '搜索': 'Search',
  '正在刷新…': 'Refreshing…',
  '正在读取音乐…': 'Loading music…',
  '重试': 'Retry',
  '没有找到“{query}”的歌曲。': 'No songs found for “{query}”.',
  '音乐库中暂无歌曲。': 'There are no songs in the library.',
  '“{query}”的歌曲': 'Songs matching “{query}”',
  '全部歌曲': 'All songs',
  '第 {page} 页 · {count} 首': 'Page {page} · {count} songs',
  '第 {page} 页 · 加载中': 'Page {page} · Loading',
  '正在加载歌曲第 {page} 页…': 'Loading song page {page}…',
  '取消收藏': 'Unfavorite',
  '加入队列': 'Add to queue',
  '歌曲上一页': 'Previous song page',
  '歌曲下一页': 'Next song page',
  '歌曲每页最多显示 30 首': 'Up to 30 songs per page',
  '艺术家列表': 'Artist list',
  '{name} 封面': '{name} cover art',
  '{count} 张专辑': '{count} albums',
  '艺术家列表加载失败。': 'Could not load the artist list.',
  '艺术家列表加载失败': 'Could not load artists',
  '艺术家详情加载失败。': 'Could not load artist details.',
  '艺术家详情加载失败': 'Could not load artist details',
  '艺术家详情': 'Artist details',
  '按服务器分页浏览': 'Browse server pages',
  '收藏艺术家': 'Favorite artist',
  '搜索艺术家': 'Search artists',
  '正在读取艺术家…': 'Loading artist…',
  '艺术家加载失败。': 'Could not load the artist.',
  '该艺术家暂无专辑。': 'This artist has no albums.',
  '年份未知': 'Year unknown',
  '{count} 首歌曲': '{count} songs',
  '正在读取艺术家列表…': 'Loading artists…',
  '没有找到“{query}”的艺术家。': 'No artists found for “{query}”.',
  '音乐库中暂无艺术家。': 'There are no artists in the library.',
  '艺术家上一页': 'Previous artist page',
  '艺术家下一页': 'Next artist page',
  '“{query}” · 第 {page} 页 · 本页 {count} 位艺术家': '“{query}” · Page {page} · {count} artists on this page',
  '第 {page} 页 · 本页 {count} 位艺术家': 'Page {page} · {count} artists on this page',
  '音乐库加载失败。': 'Could not load the music library.',
  '音乐库加载失败': 'Could not load the music library',
  '专辑详情加载失败。': 'Could not load album details.',
  '专辑详情加载失败': 'Could not load album details',
  '专辑详情': 'Album details',
  '真实 OpenSubsonic 数据': 'Live OpenSubsonic data',
  '取消收藏专辑': 'Unfavorite album',
  '收藏专辑': 'Favorite album',
  '搜索专辑': 'Search albums',
  '正在读取专辑…': 'Loading album…',
  '歌曲列表': 'Song list',
  '加入队列 {title}': 'Add {title} to queue',
  '播放 {title}': 'Play {title}',
  '正在读取音乐库…': 'Loading music library…',
  '没有找到“{query}”的专辑。': 'No albums found for “{query}”.',
  '音乐库中暂无专辑。': 'There are no albums in the library.',
  '上一页': 'Previous page',
  '下一页': 'Next page',
  '“{query}” · 第 {page} 页 · 本页 {count} 张专辑': '“{query}” · Page {page} · {count} albums on this page',
  '第 {page} 页 · 本页 {count} 张专辑': 'Page {page} · {count} albums on this page',
  '请输入服务器连接信息。': 'Enter your server connection details.',
  '无法读取已保存服务器，请重新启动 Sonavi。': 'Could not read saved servers. Restart Sonavi.',
  '服务器列表读取失败': 'Could not load server list',
  '正在使用系统加密保存的账号连接…': 'Connecting with an account protected by system encryption…',
  '已保存服务器连接失败': 'Could not connect to saved server',
  '已保存账号连接失败。': 'Could not connect with the saved account.',
  '已使用系统加密保存的账号重新连接。': 'Reconnected with the account protected by system encryption.',
  '无法验证重新连接结果，请重新启动 Sonavi。': 'Could not verify the reconnection result. Restart Sonavi.',
  '重新连接失败': 'Reconnection failed',
  '已删除保存的服务器。': 'Deleted the saved server.',
  '无法删除已保存服务器，请重试。': 'Could not delete the saved server. Try again.',
  '删除失败': 'Delete failed',
  '正在安全地检查服务器…': 'Securely checking the server…',
  '连接失败': 'Connection failed',
  '请检查连接信息后重试。': 'Check the connection details and try again.',
  '凭据已使用系统加密保存。': 'Credentials were saved with system encryption.',
  '系统加密存储不可用，本次会话可用，未写入明文。': 'System-encrypted storage is unavailable. This session remains usable and no plaintext was written.',
  '凭据仅用于本次会话。': 'Credentials are used for this session only.',
  '已连接 {server}，发现 {count} 个音乐文件夹。{persistence}': 'Connected to {server}. Found {count} music folders. {persistence}',
  '无法验证应用返回的连接结果，请重新启动 Sonavi。': 'Could not verify the connection result returned by the application. Restart Sonavi.',
  '请输入密码以更新这个服务器账号。': 'Enter the password to update this server account.',
  '更新服务器账号': 'Update server account',
  '添加服务器': 'Add server',
  '连接你的音乐空间': 'Connect your music space',
  '添加 Navidrome、Subsonic 或 OpenSubsonic 服务器。已保存账号可直接切换，密码不会回填到 renderer。': 'Add a Navidrome, Subsonic, or OpenSubsonic server. Saved accounts can be selected directly, and passwords are never returned to the renderer.',
  '已保存服务器': 'Saved servers',
  '正在读取系统加密保存的账号…': 'Loading accounts protected by system encryption…',
  '默认': 'Default',
  '连接 {server} · {username}': 'Connect to {server} · {username}',
  '正在连接…': 'Connecting…',
  '连接': 'Connect',
  '删除 {server} · {username}': 'Delete {server} · {username}',
  '删除': 'Delete',
  '服务器地址': 'Server address',
  '支持 HTTPS、自定义端口与子路径；不会绕过 TLS 证书验证。': 'Supports HTTPS, custom ports, and subpaths. TLS certificate validation is never bypassed.',
  '用户名': 'Username',
  '密码': 'Password',
  '在这台 {platform} 设备上记住我': 'Remember me on this {platform} device',
  '允许不加密的 HTTP（仅限我了解风险的局域网测试）': 'Allow unencrypted HTTP (local-network testing only; I understand the risks)',
  '正在测试…': 'Testing…',
  '更新并连接': 'Update and connect',
  '测试连接': 'Test connection',
  'renderer 不直接访问 Node.js；密码不会进入 localStorage、Pinia 或日志。': 'The renderer has no direct Node.js access. Passwords never enter localStorage, Pinia, or logs.',
  '删除已保存服务器？': 'Delete the saved server?',
  '将删除 {server} 的系统加密凭据，不会修改服务器数据。': 'This deletes the system-encrypted credentials for {server} without changing server data.',
  '删除服务器': 'Delete server',
  '收藏加载失败。': 'Could not load favorites.',
  '收藏加载失败': 'Could not load favorites',
  '与服务器账号实时同步，不在本机伪造收藏状态': 'Synchronized with the server account; favorite state is never fabricated locally',
  '正在读取收藏…': 'Loading favorites…',
  '还没有收藏的艺术家、专辑或歌曲。': 'No favorite artists, albums, or songs yet.',
  '歌曲': 'Songs',
  '请先选择歌曲。': 'Select a song first.',
  '歌词加载失败。': 'Could not load lyrics.',
  '歌词加载失败': 'Could not load lyrics',
  '歌词 {number}': 'Lyrics {number}',
  '版本 {number}': 'Version {number}',
  '同步': 'Synced',
  '文本': 'Text',
  '歌词': 'Lyrics',
  '未选择歌曲': 'No song selected',
  '关闭': 'Close',
  '正在读取歌词…': 'Loading lyrics…',
  '服务器没有返回这首歌的歌词。': 'The server returned no lyrics for this song.',
  '歌词版本': 'Lyrics version',
  '空闲': 'Idle',
  '正在加载': 'Loading',
  '正在播放': 'Playing',
  '已暂停': 'Paused',
  '正在缓冲': 'Buffering',
  '正在跳转': 'Seeking',
  '播放结束': 'Playback ended',
  '播放错误': 'Playback error',
  '未知格式': 'Unknown format',
  '{format} → MP3 · 兼容转码': '{format} → MP3 · Compatible transcoding',
  '{format} · 原始音频': '{format} · Original audio',
  '单曲循环': 'Repeat one',
  '列表循环': 'Repeat all',
  '不循环': 'Repeat off',
  '播放器': 'Player',
  '播放队列': 'Play queue',
  '{count} 项 · {order}': '{count} items · {order}',
  '随机': 'Shuffle',
  '顺序': 'In order',
  '清空': 'Clear',
  '队列为空。': 'The queue is empty.',
  '播放队列中的 {title}': 'Play {title} from the queue',
  '上移 {title}': 'Move {title} up',
  '下移 {title}': 'Move {title} down',
  '从队列移除 {title}': 'Remove {title} from the queue',
  '选择歌曲开始播放': 'Choose a song to start playback',
  '重试播放': 'Retry playback',
  '关闭随机播放': 'Turn shuffle off',
  '开启随机播放': 'Turn shuffle on',
  '继续播放': 'Resume playback',
  '{mode}，点击切换循环模式': '{mode}; click to change repeat mode',
  '播放进度': 'Playback progress',
  '当前播放策略无法安全跳转；可在设置中选择原始模式，或使用支持 transcodeOffset 的服务器。': 'The current playback policy cannot seek safely. Select original audio in Settings or use a server that supports transcodeOffset.',
  '音量': 'Volume',
  '系统未能开始播放，请重试。': 'The system could not start playback. Try again.',
  '音频流加载失败。': 'Could not load the audio stream.',
  '音频缓冲时间过长，已停止旧连接并尝试恢复。': 'Audio buffering took too long. The old connection was stopped and recovery was attempted.',
  '原始音频解码失败，正在进行一次兼容转码。': 'Original audio decoding failed. Trying compatible transcoding once.',
  '播放记录暂时未同步；音乐播放不受影响。': 'Playback history could not be synced yet. Music playback is unaffected.',
  '收藏操作失败。': 'Could not update the favorite.',
  '收藏操作失败': 'Could not update favorite',
  '收藏 {title}': 'Favorite {title}',
  '取消收藏 {title}': 'Unfavorite {title}',
  '歌单加载失败。': 'Could not load playlists.',
  '歌单加载失败': 'Could not load playlists',
  '歌单详情加载失败。': 'Could not load playlist details.',
  '歌单详情加载失败': 'Could not load playlist details',
  '歌单操作失败。': 'Could not update the playlist.',
  '歌单操作失败': 'Could not update playlist',
  '歌单已创建。': 'Playlist created.',
  '歌单信息已更新。': 'Playlist details updated.',
  '已追加 {count} 首歌曲。': 'Added {count} songs.',
  '歌曲已从歌单移除。': 'Song removed from the playlist.',
  '歌单已删除。': 'Playlist deleted.',
  '歌单详情': 'Playlist details',
  '所有写操作直接同步服务器；权限不足时不会修改本地显示。': 'All changes are synced directly to the server. The local view remains unchanged if permission is denied.',
  '新歌单名称': 'New playlist name',
  '例如：夜间聆听': 'For example: Evening listening',
  '包含当前队列（{count} 首，重复歌曲会保留）': 'Include the current queue ({count} songs; duplicates are preserved)',
  '创建歌单': 'Create playlist',
  '正在读取歌单…': 'Loading playlists…',
  '服务器中暂无歌单。': 'There are no playlists on the server.',
  '{count} 首 · {visibility}': '{count} songs · {visibility}',
  '公开': 'Public',
  '私有': 'Private',
  '当前账号': 'Current account',
  '正在读取歌单详情…': 'Loading playlist details…',
  '名称': 'Name',
  '对服务器上的其他用户公开': 'Visible to other users on the server',
  '保存信息': 'Save details',
  '播放全部': 'Play all',
  '追加当前队列': 'Add current queue',
  '删除歌单': 'Delete playlist',
  '这个歌单还没有歌曲。': 'This playlist has no songs.',
  '移除': 'Remove',
  '删除歌单“{name}”？': 'Delete playlist “{name}”?',
  '此操作会同步到服务器，删除后无法在 Sonavi 中撤销。': 'This change is synced to the server and cannot be undone in Sonavi.',
  '无法删除已保存服务器；当前连接不能从这里删除。': 'Could not delete the saved server. The active connection cannot be deleted here.',
  '服务器管理': 'Server management',
  '保存最多 20 个系统加密账号，并在同一个播放宿主中安全切换。': 'Save up to 20 accounts with system encryption and switch safely within one playback host.',
  '当前连接': 'Current connection',
  '本次会话未保存': 'Not saved for this session',
  '正在读取已保存服务器…': 'Loading saved servers…',
  '尚未保存服务器。点击“添加服务器”并勾选“记住我”。': 'No servers have been saved. Select “Add server” and enable “Remember me”.',
  '当前': 'Current',
  '编辑 {server} · {username}': 'Edit {server} · {username}',
  '更新凭据': 'Update credentials',
  '切换到 {server} · {username}': 'Switch to {server} · {username}',
  '切换': 'Switch',
  '切换成功后旧连接、媒体句柄和查询缓存会失效；连接失败时仍保留当前会话。删除只作用于本机加密凭据，不修改服务器数据。': 'After a successful switch, the old connection, media handles, and query cache are invalidated. The current session remains active if the connection fails. Deleting removes only locally encrypted credentials and does not change server data.',
  '切换服务器？': 'Switch servers?',
  '将切换到 {server}（{username}）。成功后会停止当前播放并加载目标服务器；连接失败时保留当前会话。': 'Switch to {server} ({username}). A successful connection stops current playback and loads the target server; the current session remains active if it fails.',
  '确认切换': 'Switch server',
  '第一页': 'First page',
  '最后一页': 'Last page',
  '更多页': 'More pages',
  '滑块': 'Slider',
  '导出 Sonavi 连接诊断': 'Export Sonavi connection diagnostics',
  '{stream}。{reason}': '{stream}. {reason}',
  '{count} 项': '{count} items',
  '请求成功，无需操作。': 'The request succeeded. No action is needed.',
  '检查服务器证书、系统时间与证书链；Sonavi 不会忽略证书错误。': 'Check the server certificate, system time, and certificate chain. Sonavi never ignores certificate errors.',
  '服务器要求 HTTP 身份验证，请检查反向代理配置。': 'The server requires HTTP authentication. Check the reverse proxy configuration.',
  '服务器拒绝访问，请检查账号权限与反向代理规则。': 'The server denied access. Check account permissions and reverse proxy rules.',
  '检查服务器状态和反向代理日志后重试。': 'Check the server status and reverse proxy logs, then try again.',
  '服务器以 HTTP 200 返回了协议错误体，请检查服务端日志和该端点支持情况。': 'The server returned a protocol error body with HTTP 200. Check server logs and endpoint support.',
  '服务器返回了非预期内容，可能是登录页、代理错误页或协议错误体。': 'The server returned unexpected content, such as a sign-in page, proxy error page, or protocol error body.',
  '音频流在传输中断开，请检查网络、代理和服务器转码日志。': 'The audio stream was interrupted. Check the network, proxy, and server transcoding logs.',
  '请求在超时时间内没有收到服务器响应，请检查网络、代理与服务器负载后重试。': 'The server did not respond before the timeout. Check the network, proxy, and server load, then try again.',
  '请求已因切换连接、代理或播放项目而取消。': 'The request was cancelled because the connection, proxy, or playing item changed.',
  '检查网络与代理设置；代理失败时 Sonavi 不会静默改为直连。': 'Check network and proxy settings. Sonavi never silently falls back to a direct connection when the proxy fails.',
  '已收到响应头，但正文读取超时；请检查反向代理响应缓冲、上游读取与服务器负载。': 'Response headers arrived, but reading the body timed out. Check reverse proxy buffering, upstream reads, and server load.',
  '播放器进入缓冲；等待对应的 buffer-end 记录持续时间。': 'The player started buffering. Check the matching buffer-end entry for its duration.',
  '播放器已退出缓冲；请结合持续时间与相邻音频流记录判断链路稳定性。': 'The player stopped buffering. Compare its duration with nearby audio stream entries to assess connection stability.',
  '无法读取歌词，请稍后重试。': 'Could not load lyrics. Try again later.',
  '播放记录暂时无法同步。': 'Playback history could not be synced yet.',
  '连接会话已失效，请重新连接服务器。': 'The connection session expired. Reconnect to the server.',
  '服务器已返回响应头，但正文读取超时；请检查服务器负载与反向代理响应缓冲。': 'Response headers arrived, but reading the body timed out. Check server load and reverse proxy buffering.',
  '服务器响应超时，请检查地址与网络。': 'The server response timed out. Check the address and network.',
  '无法解析服务器域名。': 'Could not resolve the server domain name.',
  '服务器拒绝连接，请检查地址和端口。': 'The server refused the connection. Check the address and port.',
  'TLS 证书验证失败，Sonavi 不会绕过证书检查。': 'TLS certificate validation failed. Sonavi never bypasses certificate checks.',
  '无法连接服务器，请检查网络与服务器地址。': 'Could not connect to the server. Check the network and server address.',
  '服务器要求重定向；请直接填写最终服务器地址。': 'The server requested a redirect. Enter the final server address directly.',
  '上游 HTTP 认证拒绝了请求。': 'Upstream HTTP authentication rejected the request.',
  '服务器前置防护要求浏览器挑战，桌面客户端无法完成该挑战。': 'The server protection requires a browser challenge that the desktop client cannot complete.',
  '服务器或反向代理拒绝了请求。': 'The server or reverse proxy rejected the request.',
  '服务器暂时出错，请稍后重试。': 'The server encountered a temporary error. Try again later.',
  '服务器返回了网页而不是 Subsonic JSON。': 'The server returned a web page instead of Subsonic JSON.',
  '服务器返回的内容不是有效 JSON。': 'The server response is not valid JSON.',
  '服务器响应不符合 Subsonic 协议。': 'The server response does not conform to the Subsonic protocol.',
  '用户名、密码或 API 凭据不正确。': 'The username, password, or API credentials are incorrect.',
  '服务器不支持 Sonavi 使用的安全认证方式。': 'The server does not support the secure authentication method used by Sonavi.',
  '当前账号无权执行此操作。': 'The current account is not allowed to perform this action.',
  '客户端与服务器的 Subsonic 协议版本不兼容。': 'The client and server use incompatible Subsonic protocol versions.',
  '服务器报告 Subsonic 请求失败。': 'The server reported that the Subsonic request failed.',
  '服务器未返回专辑详情。': 'The server did not return album details.',
  '服务器未返回艺术家详情。': 'The server did not return artist details.',
  '服务器未返回歌单详情。': 'The server did not return playlist details.',
  '服务器响应超过安全大小限制。': 'The server response exceeded the safe size limit.',
  '手动代理地址不是有效 URL。': 'The manual proxy address is not a valid URL.',
  '手动代理仅支持 HTTP、HTTPS、SOCKS4 或 SOCKS5。': 'The manual proxy supports only HTTP, HTTPS, SOCKS4, or SOCKS5.',
  '手动代理暂不接受 URL 内嵌账号或密码。': 'The manual proxy does not accept a username or password embedded in the URL.',
  '手动代理必须包含主机和端口，且不能包含路径。': 'The manual proxy must include a host and port and cannot include a path.',
  '手动代理不能包含查询参数或片段。': 'The manual proxy cannot include query parameters or a fragment.',
  '按设置请求原始音频，不进行转码。': 'Request original audio as configured, without transcoding.',
  '自动策略优先使用已知媒体类型的原始音频；解码失败时仅重试一次兼容转码。': 'Automatic mode prefers original audio for known media types and retries compatible transcoding only once after a decoding failure.',
  '已保存的服务器不存在或凭据无法解密。': 'The saved server does not exist or its credentials could not be decrypted.',
  '连接检查失败，请稍后重试。': 'The connection check failed. Try again later.',
  '服务器地址不是有效 URL。': 'The server address is not a valid URL.',
  '服务器地址只支持 HTTPS 或 HTTP。': 'The server address supports only HTTPS or HTTP.',
  'HTTP 不会加密凭据，请明确允许后再连接。': 'HTTP does not encrypt credentials. Explicitly allow it before connecting.',
  '服务器地址不能包含账号、查询参数或片段。': 'The server address cannot include credentials, query parameters, or a fragment.',
  '按默认策略请求原始音频。': 'Request original audio using the default policy.',
  '无法读取音乐库，请稍后重试。': 'Could not load the music library. Try again later.'
}

const ENGLISH_PATTERNS: ReadonlyArray<readonly [RegExp, string]> = [
  [/^服务器返回了 HTTP (\d+)。$/, 'The server returned HTTP $1.'],
  [/^请求 MP3 兼容转码，最高 (\d+) kbps。$/, 'Request compatible MP3 transcoding at up to $1 kbps.'],
  [/^自动策略未确认该格式可直接播放，使用 MP3 兼容转码，最高 (\d+) kbps。$/, 'Automatic mode could not confirm direct playback for this format, so it uses compatible MP3 transcoding at up to $1 kbps.']
]

export function translate(
  language: AppLanguage,
  source: string,
  values: TranslationValues = {}
): string {
  let template = language === 'en-US' ? (ENGLISH_MESSAGES[source] ?? source) : source
  if (language === 'en-US' && template === source) {
    for (const [pattern, replacement] of ENGLISH_PATTERNS) {
      if (pattern.test(source)) {
        template = source.replace(pattern, replacement)
        break
      }
    }
  }
  return template.replace(/\{([a-zA-Z][a-zA-Z0-9]*)\}/g, (match, key: string) =>
    Object.hasOwn(values, key) ? String(values[key]) : match
  )
}

export function hasEnglishTranslation(source: string): boolean {
  return Object.hasOwn(ENGLISH_MESSAGES, source)
}
